ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACQUISITION_REQUEST_NEW';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACQUISITION_REQUEST_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUGGESTION_NEW';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUGGESTION_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FAQ_PUBLISHED';
